version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    restart: always
    depends_on:
      - sql

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80

  database:
    image: mariadb:latest
    container_name: sql
    volumes:
      - /var/lib/mysql:/dataSQL/db
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: agencedb
      MARIADB_ROOT_PASSWORD: root
    restart: always